### ISSUE TITLE
Usage of Wire library.

### ISSUE THREAD

**Issue by Koepel** [jfomhover/TCS3414Lib#1]
Hi, I have made a wiki with the most common mistakes when using the Arduino Wire library. You have the three most common mistakes in the file "TCS3414Lib/TCS3414Lib.cpp".
You can remove all the `while (Wire.available() < 8);` and you can remove the Wire.beginTransmission() and Wire.endTransmission() that are used together with Wire.requestFrom().
Explanation: [Common-mistakes](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes), number 1, 2 and 3.

**Comment by jfomhover** [comment]
Thanks this was very helpful, I didn't know those details and learning about the Wire library on my own. I updated the lib.
